### ISSUE TITLE
Decimation feature is missing from cats

### ISSUE THREAD

**Issue by FightingBlaze** [teamneoneko/Cats-Blender-Plugin#103]
It was there at first, then when I used it on a shorts model, then tried to weight paint, then Blender crashed. Now when I try to find it its not there at all.

Tried re-installing it twice, idk where it is now, unless I'm missing something?

**Comment by RinaDev-xyz** [comment]
As stated in the Discord if your using blender 4.1 Decimation was removed if your not then please read this post first: https://github.com/unofficalcats/Cats-Blender-Plugin-Unofficial-/issues/81 before posting this as an issue.

**Comment by RinaDev-xyz** [comment]
Closed to not being a bug and is removed on Blender 4.1. Informed user on the discord as there asked for help there as well.
