### ISSUE TITLE
Warning about naming issue.

### ISSUE THREAD

**Issue by boyaom** [teamneoneko/Cats-Blender-Plugin#141]
Hi, would you kindly consider converting "mmd_tools_local_UL_" to "MMD_TOOLS_LOCAL_UL_" in the following files to ensure consistency with the expected naming convention?
    extern_tools\mmd_tools_local\operators\translations.py
    extern_tools\mmd_tools_local\panels\tool.py
    extern_tools\mmd_tools_local\panels\util_tools.py
Currently, every time I open Blender, I receive warning messages stating that "mmd_tools_local_UL_xxxx doesn't have upper case alpha-numeric prefix", even though this does not hinder the functionality. Thank you for your attention to this matter.
![image](https://github.com/user-attachments/assets/8fa849ce-1994-4739-b222-6388e6dcb334)

**Comment by RinaDev-xyz** [comment]
Fixed in latest dev branch for Blender 4.2 will backport to Blender 4.1 and  3.6 if needed later.
