### ISSUE TITLE
Eye Tracking Panel vanishes after first time use.

### ISSUE THREAD

**Issue by RinaDev-xyz** [teamneoneko/Cats-Blender-Plugin#178]
Reported by Tailslol on Discord, Eye tracking panel vanishes after using it once.

**Comment by tails101** [comment]
thanks

**Comment by RinaDev-xyz** [comment]
Has now been fixed in the dev branch for 3.6, 4.2 and 4.3. will be pushed to stable in the next week. If you want this fixed download the dev branch for your blender version. 

All i done is added a reset button, not the best solution but was the most easy thing to do.
