### ISSUE TITLE
Atlas Generation issue

### ISSUE THREAD

**Issue by Septimental** [teamneoneko/Cats-Blender-Plugin#182]
As the title suggests i'm having an issue generating the atlas for my model, im still new at this but when i use CATS to generate the atlas so that i can import the textures on my model to unity it turns my model completely black and the atlas generated is black as well. Then i tried converting the textures to a png and whenever i click the button it gives a popup saying "Converted 0 textures to png." I would be really appreciative if someone could give me a hand.

CATS Version 4.2.1.3
Blender version 4.2.1 LTS

**Comment by RinaDev-xyz** [comment]
The atlas tab is not a cats plugin and is a 3rd party plugin called material combiner which you have to download and is not included with cats, please check their github FAQ out and if your still having issues please report this issue there: https://github.com/Grim-es/material-combiner-addon

All cats does is display the Material Combiner tab in Cats UI, it does not interact with any functions of Material Combiner.

Please note the convert textures to png needs to have textures files already, all it does if convert let's say jpg files to png files and saves them next to the old files. It doesn't convert materials to png or anything like that. Though sometimes this function doesn't always work correctly, I have just tested it on several modals with jpg texture files, and it worked just fine both on Blender 3.6 and blender 4.2.

Closed as not a cats issue, if you feel like this is incorrect please feel free to re-open.
