### ISSUE TITLE
Please add automatic decimation

### ISSUE THREAD

**Issue by ms0503** [teamneoneko/Cats-Blender-Plugin#184]
Hi.

I used the official version of the Cats Blender Plugin up until Blender 4.1 (with some script fixes).
I frequently used **the automatic decimation feature**.

Since I found the unofficial version, I've been using it.
However, this version **doesn't** include that feature...

Please add that.

**Comment by RinaDev-xyz** [comment]
Hi there,

The old decimation feature is a relic of the past and didn't work well and even was starting to completely break on newer versions of blender. It was never well made and caused more issues then it fixed, this is the reason why it was removed and won't be added back.

As we are working on Avatar Toolkit to replace Cats we are no longer adding new features to cats. You can suggest this feature for Avatar Toolkit: https://github.com/teamneoneko/Avatar-Toolkit

However for the time being you can use Tuxedo, which is a plugin which came from one of the original cats developers which basically has the old decimation and smart decimation features cats used to have, just much more improved: https://github.com/feilen/tuxedo-blender-plugin

As this won't ever be added to Cats, this has been closed.
