### ISSUE TITLE
Bone merge to parents/active in an undesirable place

### ISSUE THREAD

**Issue by PapiOphidian** [teamneoneko/Cats-Blender-Plugin#186]
Description of Issue:
In order to access the feature to merge bones to their parents or to the active element, CATS currently must load every bone and seems to perform calculations to populate the To Merge enum. This is super undesirable especially if the model has loads of bones such as those exported from Koikatsu which can easily have over 2000 bones. The one I am currently working on that prompted me to write this issue has ~4700 bones. The list took >5min to populate which is more of a nuisance than a convenience.

What I'd recommend is setting it in Other Options similar to how it was in previous versions of CATS or make bone merging its own tab.

Blender Version:
4.2.2 LTS

Cats Version:
4.2.1.3

Operating System:
Windows 11

Steps to Reproduce:

Load a model with a lot of bones
Go to the Optimization tab of CATS
Go the the Bones sub tab
Observe that the menu takes a considerable amount of time to load

Screenshots or Error Messages:
N.A.

Additional Context:
N.A.

**Comment by RinaDev-xyz** [comment]
Hi there, 

Changing the UI around again will just confuse users as most users are now used to the current UI. However what I have done instead is to stop the bones loading automatically land added a load bones button instead which should fix your issue. 

This is now live on the dev branches for 3.6, 4.1 and 4.2. Will be pushed to stable in the next week or two.

Hope this is a ideal solution,
Thanks

**Comment by RinaDev-xyz** [comment]
Closed as not been pushed to stable in versions: [4.2.1.4](https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/releases/tag/4.2.1.4) [4.1.2.3](https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/releases/tag/4.1.2.3 ) [3.6.8.2](https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/releases/tag/3.6.8.2)
