### ISSUE TITLE
Attach Mesh causes exception

### ISSUE THREAD

**Issue by judy-vrc** [teamneoneko/Cats-Blender-Plugin#194]
**Description of Issue:**
When clicking 'Attach Merge' button, the exception occured.

**Blender Version:**
4.1.1

**Cats Version:**
4.1.2.4-dev

**Operating System:**
Windows 10 x64

**Steps to Reproduce:**
1、Prepare a mesh
![image](https://github.com/user-attachments/assets/6f3ffe9e-303f-4d6d-a39b-f5652ba1b21d)

2、Set up the Base & Mesh to attach to
![image](https://github.com/user-attachments/assets/e557d837-d005-4256-a555-f83c8a6c7ea8)

3、Click the 'Attach Mesh', exception occured.
![image](https://github.com/user-attachments/assets/1328adf7-3f56-4021-9256-dcc04e2c5e6c)

**Log Output:**
`Python: Traceback (most recent call last):
  File "C:\Users\Judy\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-41-dev\tools\armature_custom.py", line 167, in execute
    mesh_bone.head = Common.find_center_vector_of_vertex_group(mesh, mesh_name)
    ^^^^^^^^^^^^^^
ValueError: bpy_struct: item.attr = val: sequence expected at dimension 1, not 'bool'
`

**Comment by RinaDev-xyz** [comment]
Hi there, thanks for the report.

Though I can not re-produce your issue I have made some improvements to the attach mesh system in #196 which is now in 4.1, 4.2 and 4.3 dev branches. Please feel free to try the dev branch for Blender 4.1 to see if it resolves your issue.

This update will be pushed to stable in the next couple of weeks.

Thanks!

**Comment by RinaDev-xyz** [comment]
Closing as no response, if you still have any issues please feel free to re-open.

**Comment by judy-vrc** [comment]
Issue solved! Sorry for the late response.
