### ISSUE TITLE
使用zip上傳到Mixmao仍然沒有貼圖，這個問題怎麼解決？

### ISSUE THREAD

**Issue by Wph2000** [teamneoneko/Cats-Blender-Plugin#198]
<img width="372" alt="image" src="https://github.com/user-attachments/assets/193ecc7d-6e1e-4cfc-a9c6-1c062a40bc56">

**Comment by RinaDev-xyz** [comment]
Please use English, none of our support team can speak Chinese. please also follow the issue template: https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/issues/81 

As the template and issue rules have not been followed this issue will be closed, please open a new issue with the issue template.

**Comment by Wph2000** [comment]
Ok thank you, I updated my question～


Yusarina ***@***.***> 於 2024年11月24日 週日 下午11:25寫道：
