### ISSUE TITLE
Armature Merging - Non-uniform Scale Error

### ISSUE THREAD

**Issue by JHawkley** [teamneoneko/Cats-Blender-Plugin#234]
I'm getting an inappropriate error with v4.3.1.0 that did not occur with v4.3.0.0.  I know this, because I got the update to v4.3.1.0 while I was working, applied the update but did not restart, finished an armature merge, found out it deleted my toe end bones used to guide VRChat physbones, then restarted Blender and attempted to redo the merge in a new save file.

Now, I get an error when I attempt to perform the armature merge: "non-uniform scale detected on armature Armature"

However, the scaling _is_ uniform.  It isn't a scale of `1, 1, 1` but it is `0.547929, 0.547929, 0.547929` which is uniform.  It's also exactly the same scale as the armature to be merged.  I also copied the value to all armatures and it still complains it isn't uniformly scaled.  Sounds like a floating-pointing rounding issue somewhere...

If I temporarily set the scale to `1, 1, 1`, I can SORT OF merge the armatures, but I get an error logged to console:

```
Python: Traceback (most recent call last):
  File "C:\Users\Personal\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\cats_blender_plugin\tools\armature_custom.py", line 267, in execute
    merge_armatures(base_armature_name, merge_armature_name, False, merge_same_bones=context.scene.merge_same_bones)
  File "C:\Users\Personal\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\cats_blender_plugin\tools\armature_custom.py", line 330, in merge_armatures
    process_bones(base_armature, merge_armature, bone_map, mesh_only, merge_same_bones)
  File "C:\Users\Personal\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\cats_blender_plugin\tools\armature_custom.py", line 385, in process_bones
    handle_bone_merging(base_armature, merge_bone_data, bone_map, merge_same_bones)
  File "C:\Users\Personal\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\cats_blender_plugin\tools\armature_custom.py", line 413, in handle_bone_merging
    merge_custom_bones(base_armature, merge_bone_data, bone_map, bones_to_merge)
  File "C:\Users\Personal\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\cats_blender_plugin\tools\armature_custom.py", line 430, in merge_custom_bones
    if old_name in merge_armature.data.edit_bones and bone_name in base_armature.data.edit_bones:
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'data'
```

(I know this is not technically the same issue, but I got it while I was troubleshooting and writing this issue out.)

After rescaling to defeat this problematic check, the armatures were merged but the bones were not de-duplicated, so there's a `Hips` and `Hips.001` bone and a `Spine` and `Spine.001` bone and so on.  Basically, I have no workaround besides downgrading CATS back to v4.3.0.0.

I'll see if I can make reproduction steps/files for you.  Hopefully, I can just delete the meshes and make a set of files that will allow you to reproduce the issue without violating my license for this avatar or the artist who did my new clothing.

**Comment by RinaDev-xyz** [comment]
Hi,

Please use the dev branch for now, I reverted the Armature merge system to the old version temporary, the new system has some bugs in it which wasn't picked up during testing.

https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/tree/blender-43-dev

**Comment by JHawkley** [comment]
Alright, here are the reproduction files:
[Issue 234 - Reproduction Files.zip](https://github.com/user-attachments/files/17979398/Issue.234.-.Reproduction.Files.zip)

Here are the steps to reproduce the non-uniform scale error:
1. Open `Issue 234 - Merge Me.blend`.
2. Select the `Armature` and its contents.
3. Right-click and copy.
4. Open `Issue 234 - Target of Merge.blend`.
5. Right-click `Collection` and paste.
6. Click `Armature.001` and then ctrl+click `Armature` to select them both.
7. Use CATS to merge the armatures.
  a. I turned off all the options before merging, but you don't need to do this to get the error.
8. You should get the non-uniform scale error when you attempt the merge.

Continuing from the above point, to get the failed merge:
1. Select `Armature`.
2. In `Object Properties -> Transform`, set the scale of X, Y, and Z to `1`.
3. Select `Armature.001`.
4. In `Object Properties -> Transform`, set the scale of X, Y, and Z to `1`.
5. Click `Armature.001` and then ctrl+click `Armature` to select them both.
6. Attempt the merge using CATS again.
7. You should now get the `AttributeError: 'dict' object has no attribute 'data'` error.
8. Open `Armature` and observe the duplicated bones.

Ah, your reply just appeared for me.  I'll do that.  I hope the above is still helpful.

**Comment by RinaDev-xyz** [comment]
No worries, we were aware of the issue as it was reported in the discord, I just forgot to open a Issue here to track it.

**Comment by RinaDev-xyz** [comment]
The new system is on testing on this branch: https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/tree/Merge-Armature-Test-Blender-4.2

This one has the same improvements as the new one was meant to be but is a complete re-write. should not be as buggy I hope.

**Comment by RinaDev-xyz** [comment]
These issues should be fixed in https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/releases/tag/4.3.1.1 for Blender 4.3 and https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/releases/tag/4.2.2.1 for Blender 4.2.

Therefor I am going to close this issue.

If you still have any of the issues stated in this post please feel to re-open this issue, if you have any new issues please start a new post.

Thanks!
