### ISSUE TITLE
Separate By: Loose Shapes doesn't separate anything, despite there being loose shapes.

### ISSUE THREAD

**Issue by CaramellApll** [teamneoneko/Cats-Blender-Plugin#250]
When I use Separate by: Loose Shapes, click on the body of the model (which has loose parts such as a floating ponytail, geometry outlines, a messenger bag, etc.), nothing ends up happening. It states it separated shapes, but no results come out. I spawned 2 cubes completely apart, joined them, then hit separate by: loose parts, and nothing happens still.

Blender Version: 4.3.1

Cats Version: 4.3.1.1

Operating System: Windows 11

Steps to Reproduce:

Select a mesh, specifically on that's been merged with no Booleans.
Click Separate by : Loose Shapes

Additional Context:
For the past 3 updates, I've continued to have this issue. I have no idea how this could be happening as the program believes something has happened.

Screenshot 1 is before attempting to separate.
![Screenshot (67)](https://github.com/user-attachments/assets/cbc1296c-fe94-4ab2-bb5d-b606a35b8aa8)
Screenshot 2 is after, dialogue box "Successfully Separated Loose Parts" included.
![Screenshot (68)](https://github.com/user-attachments/assets/dbd9eee4-815f-40c8-8a46-3ffe339ad17e)
Screenshot 3 is the log info box.
![Screenshot (69)](https://github.com/user-attachments/assets/738a7819-061a-4fd6-a063-0b6065176849)

**Comment by RinaDev-xyz** [comment]
It's kinda funny, this is one of the few things I didn't touch because it was just working and it's now broken.

I take a look later and see if I can fix it on the dev branch for now.

**Comment by CaramellApll** [comment]
Thank you! Sorry for the inconvenience, hah. I guess whenever I use Cats it's always at the most inconvenient times, huh?

**Comment by RinaDev-xyz** [comment]
Hey there, this seems only a Blender 4.3 issue as well as it was working perfectly fine in Blender 4.2, so looks like good old Blender made a secret change somewhere which broke this function in 4.3, got to love it when the Blender devs don't update there docs about breaking changes.

However I just pushed a fix to the 4.3 dev branch which should fix this issue, you can download the dev branch here; https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/tree/blender-43-dev

This won't be pushed to stable unto the new year now as we are currently busy on our other project and then from tomorrow the Neoneko team is on break unto the new year. 

Let me know if there is any other issues, if there isn't close the issue.

**Comment by RinaDev-xyz** [comment]
The fix has been pushed to stable, see  https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/releases/tag/4.3.1.2

Due to this I am closing this issue, if you still have the same issue feel free to re-open!
