### ISSUE TITLE
Delete zero weight bones [proposal]

### ISSUE THREAD

**Issue by ArcPav** [teamneoneko/Cats-Blender-Plugin#44]
Can you optimize this feature a bit?
In some cases, it is necessary to retain some bones, so I added "Twist" to the names of bones that I do not want to delete, But it's obvious that this is useless

https://www.aplaybox.com/details/model/ejwBmp4y7gdm
You can download it to learn more about the situation:
View the auxiliary bones of the hand [手捩 腕捩]

I can wait for a month or longer

**Comment by RinaDev-xyz** [comment]
Hi There, can I confirm if your using Fix MMD Model or the delete Zero Weight bones button in optimize menu?

**Comment by ArcPav** [comment]
In fact, they are all similar
Optimize: delete 手捩/腕捩  hold 手捩/腕捩1~3
Fix mmd model : delete 手捩/腕捩1~3  hold 手捩/腕捩

original
![image](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/assets/76981036/5082da7d-0862-4475-bf47-ecb9a0f88cbc)

Fix mmd model
![image](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/assets/76981036/035a2bd3-5878-43f4-a5fa-883595ee524e)

Fix mmd model(Add 'Twist' to the bone name) & Optimize>Delete Zero Weight Bones
![image](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/assets/76981036/85c5a633-1c57-4c68-a2be-45af33359213)

I'm not sure, you can test it out

**Comment by RinaDev-xyz** [comment]
It seems the function to add Twist to the bones names doesn't even work in the original version of cats which I thought it did.

So I think the best thing I might be able to do is add a check so if a bone has _Twist in it's name at the end it won't delete said bone but I going to try to make it optional so the user can decide if there want to keep the twist bones or not.

I have a look at it later to see if I can add this, may take a little bit of time so my planed release for this will be version the next major version I plan to release.

**Comment by ArcPav** [comment]
This function doesn't seem to be working, or it can be said to be problematic
Unfortunately, the official version is no longer updated
Thank you for still maintaining it

**Comment by RinaDev-xyz** [comment]
Yea I don't think the official version will ever be updated again as the original author has kinda vanished and the community who was maintaining doesn't seem to want to continue (Or can't).

I am happy to maintain it as long as people are using it :)

**Comment by RinaDev-xyz** [comment]
Hey,

I have just pushed a possible fix for this issue to the dev version for blender 3.6 [here](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/tree/blender-36-dev), it adds a check box to optimization > bones called "Experimental: Keep bones with _twist" this allows the user to add _twist or Twist to bones and the button  Remove Zero Weight bones will not remove these bones if this is checked.

Please could you test and give me some feedback?

Thanks!

**Comment by ArcPav** [comment]
It seems like there's no problem now
No need to publish it immediately-Waiting for the next major version
thanks good

The current issue has been resolved. If there are any issues, I will open it again
