### ISSUE TITLE
Remove Zero Weight Bones is gone

### ISSUE THREAD

**Issue by fiveseven808** [teamneoneko/Cats-Blender-Plugin#50]
Would you be able to add the option to remove zero weight bones? I see the option in merge armatures, but I cant seem to do it without merging armatures.

**Comment by RinaDev-xyz** [comment]
This feature was never remove, please ensure you read the wiki in the future as the feature has been moved to the Optimization tab under bones.

https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/wiki/Features

![image](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/assets/104736380/b2407c9e-b4d2-4ac3-8336-1a3b19675898)

Thanks!

**Comment by fiveseven808** [comment]
Ahh, that makes sense. Thank you for pointing me to the wiki! My apologies.

**Comment by RinaDev-xyz** [comment]
No worries, I change quite a bit with cats so it's understandable it's a little confusing coming from the original! 

Thanks!
