### ISSUE TITLE
4.1.0.2 release still has a check that fails if blender version >= 4.1 

### ISSUE THREAD

**Issue by incompetentcoder** [teamneoneko/Cats-Blender-Plugin#79]
line 189 in __init__.py in the latest 4.1 release still has     if bpy.app.version >= (4, 1):

**Comment by RinaDev-xyz** [comment]
Nope it doesn't, the branch files are fine, I'm just stupid and managed to mess up the zip file for the release and included the blender 4.0 version. Should be fixed now.

**Comment by RinaDev-xyz** [comment]
Closed due to being fixed, just download the new zip. if there still any issue feel free to re-open.
