### ISSUE TITLE
Shape keys disappear when joining all meshes

### ISSUE THREAD

**Issue by MaxTheSyntax** [teamneoneko/Cats-Blender-Plugin#83]
When the "Join all meshes" button is clicked, all of the shape keys just disappear.

[Here's a video](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/assets/117991235/ce107446-07fd-4ce1-b1cc-ea09ed5c54dc)

Please tell me if I need to provide anything else.

**Comment by RinaDev-xyz** [comment]
This gives me Zero information at all please ensure you read [this](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/issues/81) post first and follow the template in there for future issues.

Second I can not re-produce this with my own fbx, pmx or blend files so more info is needed on how to re-produce this issue. It might be a good idea to look at your log files (Or open blender via the console/ cmd) to see if there are any errors. 

Thanks.

**Comment by MaxTheSyntax** [comment]
Sorry, I was in a rush and thought I could save the issue as a draft. Also now after restarting my pc everything started working, so I guess the issue fixed itself. Sorry for wasting your time, I'm a beginner.

**Comment by RinaDev-xyz** [comment]
Just a question did you restart blender after installing cats?
